In [ ]:
from numpy import argmax

data = 'hello world'
alphabet = 'abcdefghijklmnopqrstuvwxyz '

char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))

integer_encoded = [char_to_int[char] for char in data]
print(integer_encoded)

onehot_encoded = list()
for value in integer_encoded:
    letter = [0 for _ in range(len(alphabet))]
    letter[value] = 1
    onehot_encoded.append(letter)
print(onehot_encoded)

inverted = int_to_char[argmax(onehot_encoded[0])]
print(inverted)

A mapping of all possible inputs is created from char values to integer values.
This mapping is then used to encode the input strinng.
The first letter in the input is 'h'. It is encoded with the index of 7 from the alphabet array.
Then one hot encoding is done one integer character at a time.
A list of 0 values is created from the length of the alphabet so any expected character can be represented.

Next the index of specific charracters is marked with a 1.
Finally, the encoding of the first letter is inverted and the result is printed.
This is done by locating the index of the binary vector with the largest value using the NumPY argmax() function.
Then usiing the integer value in a reverse lookup table of character values to integers.

In [ ]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# define data
data = ['cold', 'cold', 'warm', 'cold', 'hot', ' hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)

# integer encoding
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

# invert
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

OneHotEncoder will return a more efficient sparse encoding.
May not be suitable for some applications, such as use with the Keras deep learning library.
In this case, disabling the sparse return type by setting the sparse=False argument.

When a predicition is recieved in the 3-value one hot encoding, it is easy to invert the transform back into the original label.

Use argmax() to locate the intex of the column with the largest value.
This is fed into the LabelEncoder to calculate the inverse transform back to a next label.

[0 0 2 0 1 1 2 0 2 1]
 
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
 
['cold']


One Hot Encode with Keras